#!/usr/local/bin/docker-compose -f
version: '2'
services:
  orderflowers:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.awslex
    image: orderflowers:dev
    ports:
    - "5060:5060/udp"
    - "11000-11100:11000-11100/udp"
    network_mode: "host"
    environment:
      LEX_EAGI_SCRIPT: "/etc/asterisk/eagi/lex_eagi.py"
      SIP_LISTEN_PORT: "5060"
      RTP_PORT_RANGE_START: "11000"
      RTP_PORT_RANGE_END: "11100"
      LEX_BOT_NAME: "OrderFlowers"
      LEX_BOT_ALIAS: "POC"
      POLLY_VOICE_ID: "Salli"
      PUBLIC_IP: 192.168.42.219 # $DOCKER_HOST
      LOCAL_NET: 172.0.0.0/8
  # googletranscribe:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.googleapi
  #   image: googletranscribe:dev
  #   ports:
  #   - "5060/udp:5060/udp"
  #   - "11000-11100/udp:11000-11100/udp"
  #   environment:
  #     LEX_EAGI_SCRIPT: "/etc/asterisk/eagi/googletranscribe.py"
  #     SIP_LISTEN_PORT: "5060"
  #     RTP_PORT_RANGE_START: "11000"
  #     RTP_PORT_RANGE_END: "11100"