#!/usr/local/bin/docker-compose -f
orderflowers:
  restart: always
  build: .
  ports:
  - "5060/udp:5060/udp"
  - "11000-11100/udp:11000-11100/udp"
  environment:
    LEX_EAGI_SCRIPT: "/etc/asterisk/eagi/lex_eagi.py"
    SIP_LISTEN_PORT: "5060"
    RTP_PORT_RANGE_START: "11000"
    RTP_PORT_RANGE_END: "11100"
    LEX_BOT_NAME: "OrderFlowers"
    LEX_BOT_ALIAS: "POC"
    POLLY_VOICE_ID: "Salli"